### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by sbussard** [mackross/GTKeyboardHelper#1]
I don't know what else to say, I followed the instructions — I added the framework and imported the header file — but it simply did nothing. I have the latest version of xcode (4.3.2) and iOS (5.1)

**Comment by mackross** [comment]
Have you tried the demo project? I'm using it in production code at
the moment. Perhaps you haven't changed the class in interface
builder?

Envoyé de mon iPhone

Le 02/05/2012 à 6:38, Stephen
reply@reply.github.com
a écrit :

**Comment by sbussard** [comment]
I found out how it is supposed to work, and that it does well. Very simple, thanks for making this! 

The error was that I could not find the documentation for all of the steps necessary to get it to work, so I assumed all that was required was to drop in the framework and import the header, as outlined in the Readme file. It wasn't obvious to me what to look for in the sample project that made it work. This may sound dumb, but would you consider copying the description of the project into the Readme file under a "usage" section? If I think I already know what a project is about, I don't always read the description.
